# niente "version:" per evitare warning
networks:
  gossipnet:
    name: gossipnet

x-node: &node
  image: gossip-node:latest
  networks: [gossipnet]
  restart: unless-stopped
  entrypoint: ["/app/entrypoint.sh"]

x-peer: &peer
  <<: *node
  depends_on:
    seed1: { condition: service_started }
    seed2: { condition: service_started }
    seed3: { condition: service_started }
  environment:
    IS_SEED: "false"
    PORT: "9002"
    CONFIG_PATH: /app/config.json
  # nessuna porta esposta per i peer

services:
  # --------- SEED NODES ----------
  seed1:
    <<: *node
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seed1
    environment:
      IS_SEED: "true"
      PORT: "9001"
      CONFIG_PATH: /app/config.json
      GRPC_ADDR: "seed1:9001"
      SEEDS: "seed1:9001,seed2:9004,seed3:9006"
    ports: ["9001:9001"]

  seed2:
    <<: *node
    container_name: seed2
    environment:
      IS_SEED: "true"
      PORT: "9004"
      CONFIG_PATH: /app/config.json
      GRPC_ADDR: "seed2:9004"
      SEEDS: "seed1:9001,seed2:9004,seed3:9006"
    ports: ["9004:9004"]

  seed3:
    <<: *node
    container_name: seed3
    environment:
      IS_SEED: "true"
      PORT: "9006"
      CONFIG_PATH: /app/config.json
      GRPC_ADDR: "seed3:9006"
      SEEDS: "seed1:9001,seed2:9004,seed3:9006"
    ports: ["9006:9006"]

  # --------- PEER NODES ----------
  # Esempio di distribuzione SEEDS (variegata). Cambia come ti serve.
  peer1:  { <<: *peer, container_name: peer1,  environment: { GRPC_ADDR: "peer1:9002",  SEEDS: "seed1:9001,seed2:9004,seed3:9006" } }
  peer2:  { <<: *peer, container_name: peer2,  environment: { GRPC_ADDR: "peer2:9003",  SEEDS: "seed1:9001,seed2:9004" } }
  peer3:  { <<: *peer, container_name: peer3,  environment: { GRPC_ADDR: "peer3:9005",  SEEDS: "seed1:9001,seed3:9006" } }
  peer4:  { <<: *peer, container_name: peer4,  environment: { GRPC_ADDR: "peer4:9007",  SEEDS: "seed2:9004,seed3:9006" } }
  peer5:  { <<: *peer, container_name: peer5,  environment: { GRPC_ADDR: "peer5:9008",  SEEDS: "seed1:9001" } }
  peer6:  { <<: *peer, container_name: peer6,  environment: { GRPC_ADDR: "peer6:9009",  SEEDS: "seed2:9004" } }
  peer7:  { <<: *peer, container_name: peer7,  environment: { GRPC_ADDR: "peer7:9010",  SEEDS: "seed3:9006" } }
  peer8:  { <<: *peer, container_name: peer8,  environment: { GRPC_ADDR: "peer8:9011",  SEEDS: "seed1:9001,seed2:9004" } }
  peer9:  { <<: *peer, container_name: peer9,  environment: { GRPC_ADDR: "peer9:9012",  SEEDS: "seed1:9001,seed3:9006" } }
  peer10: { <<: *peer, container_name: peer10, environment: { GRPC_ADDR: "peer10:9013", SEEDS: "seed2:9004,seed3:9006" } }
  peer11: { <<: *peer, container_name: peer11, environment: { GRPC_ADDR: "peer11:9014", SEEDS: "seed1:9001" } }
  peer12: { <<: *peer, container_name: peer12, environment: { GRPC_ADDR: "peer12:9015", SEEDS: "seed2:9004" } }
  peer13: { <<: *peer, container_name: peer13, environment: { GRPC_ADDR: "peer13:9016", SEEDS: "seed3:9006" } }
  peer14: { <<: *peer, container_name: peer14, environment: { GRPC_ADDR: "peer14:9017", SEEDS: "seed1:9001,seed2:9004,seed3:9006" } }
  peer15: { <<: *peer, container_name: peer15, environment: { GRPC_ADDR: "peer15:9018", SEEDS: "seed1:9001,seed2:9004" } }
  peer16: { <<: *peer, container_name: peer16, environment: { GRPC_ADDR: "peer16:9019", SEEDS: "seed1:9001,seed3:9006" } }
  peer17: { <<: *peer, container_name: peer17, environment: { GRPC_ADDR: "peer17:9020", SEEDS: "seed2:9004" } }
