// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: gossip.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PingRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingReply) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type PingReqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	TargetAddr    string                 `protobuf:"bytes,2,opt,name=target_addr,json=targetAddr,proto3" json:"target_addr,omitempty"` // dove provare il Ping indiretto
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReqRequest) Reset() {
	*x = PingReqRequest{}
	mi := &file_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReqRequest) ProtoMessage() {}

func (x *PingReqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReqRequest.ProtoReflect.Descriptor instead.
func (*PingReqRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *PingReqRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PingReqRequest) GetTargetAddr() string {
	if x != nil {
		return x.TargetAddr
	}
	return ""
}

func (x *PingReqRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type PingReqReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	TsMs          int64                  `protobuf:"varint,2,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReqReply) Reset() {
	*x = PingReqReply{}
	mi := &file_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReqReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReqReply) ProtoMessage() {}

func (x *PingReqReply) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReqReply.ProtoReflect.Descriptor instead.
func (*PingReqReply) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *PingReqReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *PingReqReply) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"` // host:port gRPC
	IsSeed        bool                   `protobuf:"varint,3,opt,name=is_seed,json=isSeed,proto3" json:"is_seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *PeerInfo) GetIsSeed() bool {
	if x != nil {
		return x.IsSeed
	}
	return false
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuPct        float64                `protobuf:"fixed64,2,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemPct        float64                `protobuf:"fixed64,3,opt,name=mem_pct,json=memPct,proto3" json:"mem_pct,omitempty"`
	GpuPct        float64                `protobuf:"fixed64,4,opt,name=gpu_pct,json=gpuPct,proto3" json:"gpu_pct,omitempty"` // -1 se GPU assente
	TsMs          int64                  `protobuf:"varint,5,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_gossip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{5}
}

func (x *Stats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Stats) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *Stats) GetMemPct() float64 {
	if x != nil {
		return x.MemPct
	}
	return 0
}

func (x *Stats) GetGpuPct() float64 {
	if x != nil {
		return x.GpuPct
	}
	return 0
}

func (x *Stats) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	MyStats       *Stats                 `protobuf:"bytes,4,opt,name=my_stats,json=myStats,proto3" json:"my_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_gossip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *JoinRequest) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *JoinRequest) GetMyStats() *Stats {
	if x != nil {
		return x.MyStats
	}
	return nil
}

type JoinReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`                                      // campione iniziale
	StatsSnapshot []*Stats               `protobuf:"bytes,2,rep,name=stats_snapshot,json=statsSnapshot,proto3" json:"stats_snapshot,omitempty"` // alcune stats fresche
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReply) Reset() {
	*x = JoinReply{}
	mi := &file_gossip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReply) ProtoMessage() {}

func (x *JoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReply.ProtoReflect.Descriptor instead.
func (*JoinReply) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{7}
}

func (x *JoinReply) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *JoinReply) GetStatsSnapshot() []*Stats {
	if x != nil {
		return x.StatsSnapshot
	}
	return nil
}

type AvailBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*Stats               `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailBatch) Reset() {
	*x = AvailBatch{}
	mi := &file_gossip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailBatch) ProtoMessage() {}

func (x *AvailBatch) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailBatch.ProtoReflect.Descriptor instead.
func (*AvailBatch) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{8}
}

func (x *AvailBatch) GetStats() []*Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type JobSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CpuPct        float64                `protobuf:"fixed64,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`            // richiesta in % (0..100)
	MemPct        float64                `protobuf:"fixed64,4,opt,name=mem_pct,json=memPct,proto3" json:"mem_pct,omitempty"`            // richiesta in % (0..100)
	GpuPct        float64                `protobuf:"fixed64,5,opt,name=gpu_pct,json=gpuPct,proto3" json:"gpu_pct,omitempty"`            // richiesta in % (0..100, 0 se non serve; -1 non usato qui)
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // durata in millisecondi di tempo SIM
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`                              // libero (debug)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSpec) Reset() {
	*x = JobSpec{}
	mi := &file_gossip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSpec) ProtoMessage() {}

func (x *JobSpec) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSpec.ProtoReflect.Descriptor instead.
func (*JobSpec) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{9}
}

func (x *JobSpec) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSpec) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *JobSpec) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *JobSpec) GetMemPct() float64 {
	if x != nil {
		return x.MemPct
	}
	return 0
}

func (x *JobSpec) GetGpuPct() float64 {
	if x != nil {
		return x.GpuPct
	}
	return 0
}

func (x *JobSpec) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *JobSpec) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *JobSpec               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_gossip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{10}
}

func (x *ProbeRequest) GetJob() *JobSpec {
	if x != nil {
		return x.Job
	}
	return nil
}

type ProbeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	WillAccept    bool                   `protobuf:"varint,2,opt,name=will_accept,json=willAccept,proto3" json:"will_accept,omitempty"`     // true se il nodo può riservare quanto richiesto
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`                                // più alto = meglio (headroom residuo)
	HeadroomCpu   float64                `protobuf:"fixed64,4,opt,name=headroom_cpu,json=headroomCpu,proto3" json:"headroom_cpu,omitempty"` // % libera stimata (0..100)
	HeadroomMem   float64                `protobuf:"fixed64,5,opt,name=headroom_mem,json=headroomMem,proto3" json:"headroom_mem,omitempty"` // % libera stimata (0..100)
	HeadroomGpu   float64                `protobuf:"fixed64,6,opt,name=headroom_gpu,json=headroomGpu,proto3" json:"headroom_gpu,omitempty"` // % libera stimata (0..100; -1 se GPU assente)
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`                                // motivazione (se rifiuto)
	TsMs          int64                  `protobuf:"varint,8,opt,name=ts_ms,json=tsMs,proto3" json:"ts_ms,omitempty"`                       // tempo SIM del peer che risponde
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeReply) Reset() {
	*x = ProbeReply{}
	mi := &file_gossip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeReply) ProtoMessage() {}

func (x *ProbeReply) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeReply.ProtoReflect.Descriptor instead.
func (*ProbeReply) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{11}
}

func (x *ProbeReply) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ProbeReply) GetWillAccept() bool {
	if x != nil {
		return x.WillAccept
	}
	return false
}

func (x *ProbeReply) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProbeReply) GetHeadroomCpu() float64 {
	if x != nil {
		return x.HeadroomCpu
	}
	return 0
}

func (x *ProbeReply) GetHeadroomMem() float64 {
	if x != nil {
		return x.HeadroomMem
	}
	return 0
}

func (x *ProbeReply) GetHeadroomGpu() float64 {
	if x != nil {
		return x.HeadroomGpu
	}
	return 0
}

func (x *ProbeReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProbeReply) GetTsMs() int64 {
	if x != nil {
		return x.TsMs
	}
	return 0
}

type CommitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"` // destinazione (peer che deve eseguire)
	CpuPct        float64                `protobuf:"fixed64,3,opt,name=cpu_pct,json=cpuPct,proto3" json:"cpu_pct,omitempty"`
	MemPct        float64                `protobuf:"fixed64,4,opt,name=mem_pct,json=memPct,proto3" json:"mem_pct,omitempty"`
	GpuPct        float64                `protobuf:"fixed64,5,opt,name=gpu_pct,json=gpuPct,proto3" json:"gpu_pct,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"` // tempo SIM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_gossip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{12}
}

func (x *CommitRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommitRequest) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

func (x *CommitRequest) GetCpuPct() float64 {
	if x != nil {
		return x.CpuPct
	}
	return 0
}

func (x *CommitRequest) GetMemPct() float64 {
	if x != nil {
		return x.MemPct
	}
	return 0
}

func (x *CommitRequest) GetGpuPct() float64 {
	if x != nil {
		return x.GpuPct
	}
	return 0
}

func (x *CommitRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type CommitReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitReply) Reset() {
	*x = CommitReply{}
	mi := &file_gossip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitReply) ProtoMessage() {}

func (x *CommitReply) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitReply.ProtoReflect.Descriptor instead.
func (*CommitReply) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{13}
}

func (x *CommitReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommitReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ToNodeId      string                 `protobuf:"bytes,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_gossip_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{14}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelRequest) GetToNodeId() string {
	if x != nil {
		return x.ToNodeId
	}
	return ""
}

type CancelReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelReply) Reset() {
	*x = CancelReply{}
	mi := &file_gossip_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReply) ProtoMessage() {}

func (x *CancelReply) ProtoReflect() protoreflect.Message {
	mi := &file_gossip_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReply.ProtoReflect.Descriptor instead.
func (*CancelReply) Descriptor() ([]byte, []int) {
	return file_gossip_proto_rawDescGZIP(), []int{15}
}

func (x *CancelReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CancelReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gossip_proto protoreflect.FileDescriptor

const file_gossip_proto_rawDesc = "" +
	"\n" +
	"\fgossip.proto\x12\x06gossip\"8\n" +
	"\vPingRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"0\n" +
	"\tPingReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\"\\\n" +
	"\x0ePingReqRequest\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x1f\n" +
	"\vtarget_addr\x18\x02 \x01(\tR\n" +
	"targetAddr\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"3\n" +
	"\fPingReqReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x13\n" +
	"\x05ts_ms\x18\x02 \x01(\x03R\x04tsMs\"P\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x17\n" +
	"\ais_seed\x18\x03 \x01(\bR\x06isSeed\"\x80\x01\n" +
	"\x05Stats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\acpu_pct\x18\x02 \x01(\x01R\x06cpuPct\x12\x17\n" +
	"\amem_pct\x18\x03 \x01(\x01R\x06memPct\x12\x17\n" +
	"\agpu_pct\x18\x04 \x01(\x01R\x06gpuPct\x12\x13\n" +
	"\x05ts_ms\x18\x05 \x01(\x03R\x04tsMs\"\x86\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12 \n" +
	"\vincarnation\x18\x03 \x01(\x04R\vincarnation\x12(\n" +
	"\bmy_stats\x18\x04 \x01(\v2\r.gossip.StatsR\amyStats\"i\n" +
	"\tJoinReply\x12&\n" +
	"\x05peers\x18\x01 \x03(\v2\x10.gossip.PeerInfoR\x05peers\x124\n" +
	"\x0estats_snapshot\x18\x02 \x03(\v2\r.gossip.StatsR\rstatsSnapshot\"1\n" +
	"\n" +
	"AvailBatch\x12#\n" +
	"\x05stats\x18\x01 \x03(\v2\r.gossip.StatsR\x05stats\"\xbd\x01\n" +
	"\aJobSpec\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x01R\x06cpuPct\x12\x17\n" +
	"\amem_pct\x18\x04 \x01(\x01R\x06memPct\x12\x17\n" +
	"\agpu_pct\x18\x05 \x01(\x01R\x06gpuPct\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"1\n" +
	"\fProbeRequest\x12!\n" +
	"\x03job\x18\x01 \x01(\v2\x0f.gossip.JobSpecR\x03job\"\xf2\x01\n" +
	"\n" +
	"ProbeReply\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vwill_accept\x18\x02 \x01(\bR\n" +
	"willAccept\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12!\n" +
	"\fheadroom_cpu\x18\x04 \x01(\x01R\vheadroomCpu\x12!\n" +
	"\fheadroom_mem\x18\x05 \x01(\x01R\vheadroomMem\x12!\n" +
	"\fheadroom_gpu\x18\x06 \x01(\x01R\vheadroomGpu\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x13\n" +
	"\x05ts_ms\x18\b \x01(\x03R\x04tsMs\"\xb0\x01\n" +
	"\rCommitRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\x12\x17\n" +
	"\acpu_pct\x18\x03 \x01(\x01R\x06cpuPct\x12\x17\n" +
	"\amem_pct\x18\x04 \x01(\x01R\x06memPct\x12\x17\n" +
	"\agpu_pct\x18\x05 \x01(\x01R\x06gpuPct\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"5\n" +
	"\vCommitReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"D\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\n" +
	"to_node_id\x18\x02 \x01(\tR\btoNodeId\"5\n" +
	"\vCancelReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xf9\x02\n" +
	"\x06Gossip\x12.\n" +
	"\x04Join\x12\x13.gossip.JoinRequest\x1a\x11.gossip.JoinReply\x12.\n" +
	"\x04Ping\x12\x13.gossip.PingRequest\x1a\x11.gossip.PingReply\x127\n" +
	"\aPingReq\x12\x16.gossip.PingReqRequest\x1a\x14.gossip.PingReqReply\x127\n" +
	"\rExchangeAvail\x12\x12.gossip.AvailBatch\x1a\x12.gossip.AvailBatch\x121\n" +
	"\x05Probe\x12\x14.gossip.ProbeRequest\x1a\x12.gossip.ProbeReply\x124\n" +
	"\x06Commit\x12\x15.gossip.CommitRequest\x1a\x13.gossip.CommitReply\x124\n" +
	"\x06Cancel\x12\x15.gossip.CancelRequest\x1a\x13.gossip.CancelReplyB%Z#GossipSystemUtilization/proto;protob\x06proto3"

var (
	file_gossip_proto_rawDescOnce sync.Once
	file_gossip_proto_rawDescData []byte
)

func file_gossip_proto_rawDescGZIP() []byte {
	file_gossip_proto_rawDescOnce.Do(func() {
		file_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)))
	})
	return file_gossip_proto_rawDescData
}

var file_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gossip_proto_goTypes = []any{
	(*PingRequest)(nil),    // 0: gossip.PingRequest
	(*PingReply)(nil),      // 1: gossip.PingReply
	(*PingReqRequest)(nil), // 2: gossip.PingReqRequest
	(*PingReqReply)(nil),   // 3: gossip.PingReqReply
	(*PeerInfo)(nil),       // 4: gossip.PeerInfo
	(*Stats)(nil),          // 5: gossip.Stats
	(*JoinRequest)(nil),    // 6: gossip.JoinRequest
	(*JoinReply)(nil),      // 7: gossip.JoinReply
	(*AvailBatch)(nil),     // 8: gossip.AvailBatch
	(*JobSpec)(nil),        // 9: gossip.JobSpec
	(*ProbeRequest)(nil),   // 10: gossip.ProbeRequest
	(*ProbeReply)(nil),     // 11: gossip.ProbeReply
	(*CommitRequest)(nil),  // 12: gossip.CommitRequest
	(*CommitReply)(nil),    // 13: gossip.CommitReply
	(*CancelRequest)(nil),  // 14: gossip.CancelRequest
	(*CancelReply)(nil),    // 15: gossip.CancelReply
}
var file_gossip_proto_depIdxs = []int32{
	5,  // 0: gossip.JoinRequest.my_stats:type_name -> gossip.Stats
	4,  // 1: gossip.JoinReply.peers:type_name -> gossip.PeerInfo
	5,  // 2: gossip.JoinReply.stats_snapshot:type_name -> gossip.Stats
	5,  // 3: gossip.AvailBatch.stats:type_name -> gossip.Stats
	9,  // 4: gossip.ProbeRequest.job:type_name -> gossip.JobSpec
	6,  // 5: gossip.Gossip.Join:input_type -> gossip.JoinRequest
	0,  // 6: gossip.Gossip.Ping:input_type -> gossip.PingRequest
	2,  // 7: gossip.Gossip.PingReq:input_type -> gossip.PingReqRequest
	8,  // 8: gossip.Gossip.ExchangeAvail:input_type -> gossip.AvailBatch
	10, // 9: gossip.Gossip.Probe:input_type -> gossip.ProbeRequest
	12, // 10: gossip.Gossip.Commit:input_type -> gossip.CommitRequest
	14, // 11: gossip.Gossip.Cancel:input_type -> gossip.CancelRequest
	7,  // 12: gossip.Gossip.Join:output_type -> gossip.JoinReply
	1,  // 13: gossip.Gossip.Ping:output_type -> gossip.PingReply
	3,  // 14: gossip.Gossip.PingReq:output_type -> gossip.PingReqReply
	8,  // 15: gossip.Gossip.ExchangeAvail:output_type -> gossip.AvailBatch
	11, // 16: gossip.Gossip.Probe:output_type -> gossip.ProbeReply
	13, // 17: gossip.Gossip.Commit:output_type -> gossip.CommitReply
	15, // 18: gossip.Gossip.Cancel:output_type -> gossip.CancelReply
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gossip_proto_init() }
func file_gossip_proto_init() {
	if File_gossip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gossip_proto_rawDesc), len(file_gossip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gossip_proto_goTypes,
		DependencyIndexes: file_gossip_proto_depIdxs,
		MessageInfos:      file_gossip_proto_msgTypes,
	}.Build()
	File_gossip_proto = out.File
	file_gossip_proto_goTypes = nil
	file_gossip_proto_depIdxs = nil
}
